package infer

import (
	"bytes"
	"fmt"
	"sort"

	"github.com/AxeForging/structlint/internal/validator"
)

// Generate produces YAML bytes for a .structlint.yaml derived from the
// actual tree at root. The result is a faithful baseline: running
// `structlint validate` on the same tree with this config must exit 0.
//
// The config file itself is about to be written to disk, so *.yaml is
// force-added to allowed patterns even if no yaml files existed before —
// otherwise the very first `validate` would reject the config we wrote.
func Generate(root string) ([]byte, error) {
	tree := validator.Snapshot(root, DefaultIgnore)
	if tree == nil {
		return nil, fmt.Errorf("failed to snapshot %s", root)
	}
	allowedFiles := AllowedFilePatterns(tree)
	allowedFiles = ensurePattern(allowedFiles, "*.yaml")
	return render(
		AllowedPaths(tree),
		allowedFiles,
		RequiredFiles(tree),
		DefaultIgnore,
	), nil
}

// ensurePattern inserts pat into list at the correct sorted position
// (extension patterns before exact names) if it isn't already present.
func ensurePattern(list []string, pat string) []string {
	for _, s := range list {
		if s == pat {
			return list
		}
	}
	// Extension patterns (start with "*.") sort before exact names in our
	// output, so slot pat into the extensions block.
	i := sort.SearchStrings(list, pat)
	out := make([]string, 0, len(list)+1)
	out = append(out, list[:i]...)
	out = append(out, pat)
	out = append(out, list[i:]...)
	return out
}

func render(allowedPaths, allowed, required, ignore []string) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, "# generated by `structlint init --infer` — a baseline of the current tree.")
	fmt.Fprintln(&b, "# `validate` passes on this file as-is; tighten incrementally.")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "dir_structure:")
	fmt.Fprintln(&b, "  allowedPaths:")
	writeStringList(&b, allowedPaths, "    ")

	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "file_naming_pattern:")
	fmt.Fprintln(&b, "  allowed:")
	writeStringList(&b, allowed, "    ")
	if len(required) > 0 {
		fmt.Fprintln(&b, "  required:")
		writeStringList(&b, required, "    ")
	}

	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "ignore:")
	sortedIgnore := append([]string(nil), ignore...)
	sort.Strings(sortedIgnore)
	writeStringList(&b, sortedIgnore, "  ")
	return b.Bytes()
}

// writeStringList emits each entry as `- "value"` at the given indent. Empty
// input writes nothing (callers guard on len > 0 where necessary).
func writeStringList(b *bytes.Buffer, list []string, indent string) {
	for _, item := range list {
		fmt.Fprintf(b, "%s- %q\n", indent, item)
	}
}
